spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: spring-cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.nhp.entity
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8081.com
info:
  app.name: spring-cloud-config01
  company.name: www.nhp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8081
spring:
  profiles: test
  application:
    name: spring-cloud-config-dept-client
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        initial-size: 5
        min-idle: 10
        max-active: 20
        max-wait: 60000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.nhp.entity
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8081.com
info:
  app.name: spring-cloud-config02
  company.name: www.nhp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$